### ISSUE TITLE
Custom attribute reference create problem with Android studio render

### ISSUE THREAD

**Issue by prazjain** [arcadefire/circled-picker#2]
Hi again,

I am trying it out now, I see when I give it custom attribute values like below:

        app:lineColor="@color/primary"
        app:textColor="@android:color/darker_gray"
        app:subLineColor="@android:color/darker_gray"

I get exceptions displayed in Android studio design view for the layout:

---
java.lang.IllegalArgumentException: Unknown color
	at android.graphics.Color.parseColor(Color.java:216)
	at org.angmarch.circledpicker.CircledPicker.drawShadow(CircledPicker.java:288)
	at org.angmarch.circledpicker.CircledPicker.onDraw(CircledPicker.java:108)
	at android.view.View.draw(View.java:15114)
	at android.view.View.draw(View.java:15022)

---

java.lang.IllegalArgumentException: Unknown color
	at android.graphics.Color.parseColor(Color.java:216)
	at org.angmarch.circledpicker.CircledPicker.drawCenteredText(CircledPicker.java:248)
	at org.angmarch.circledpicker.CircledPicker.onDraw(CircledPicker.java:110)
	at android.view.View.draw(View.java:15114)
	at android.view.View.draw(View.java:15022)

---

**Comment by prazjain** [comment]
Ok, I found out why it was happening. I had set thickness and innerThickness like this : 
        app:thickness="10dp"
        app:innerThickness="5dp"

This just hid the subLine, I set it to 
        app:thickness="7dp"
        app:innerThickness="5dp"
and its working now.
You can close this issue.
Thnx

**Comment by arcadefire** [comment]
Thanks to you. Sorry for the delay, but I was busy with work and stuff! :)
